/** Smarty functions */
export const smartyFunctions: string[] = [
	"append",
	"assign",
	"block",
	"call",
	"capture",
	"config_load",
	"counter",
	"cycle",
	"debug",
	"eval",
	"fetch",
	"for",
	"foreach", "foreachelse",
	"function",
	"html_checkboxes",
	"html_image",
	"html_options",
	"html_radios",
	"html_select_date",
	"html_select_time",
	"html_table",
	"if", "elseif", "else",
	"include", "include_php",
	"insert",
	"ldelim", "rdelim",
	"literal",
	"mailto",
	"math",
	"nocache",
//	"php",
	"section", "sectionelse",
	"setfilter",
	"strip",
	"textformat",
	"while"
];

/** Common modifiers */
export const smartyModifiers: string[] = [
	"capitalize",
	"cat",
//	"constant",
	"count",
	"count_characters",
	"count_paragraphs",
	"count_sentences",
	"count_words",
	"date_format",
	"debug_print_var",
	"default",
	"escape",
	"is_array",
	"explode",
	"from_charset",
	"htmlspecialchars",
	"implode",
	"indent",
//	"json_decode",
	"json_encode",
	"lower",
	"mb_wordwrap",
	"nl2br",
	"noprint",
	"number_format",
//	"print_r",
	"regex_replace",
	"replace",
	"round",
	"spacify",
	"str_repeat",
	"string_format",
	"strip",
	"strip_tags",
	"strlen",
	"substr",
	"to_charset",
	"truncate",
	"unescape",
	"upper",
//	"urldecode",
//	"urlencode",
//	"var_dump",
	"wordwrap"
];

/** Attributes for functions */
export const smartyFunctionAttributes: Map<string, string[]> = new Map([
	["append", ["var", "value", "index", "scope"]],
	["assign", ["var", "value", "scope"]],
	["block", ["name"]],
	["call", ["name", "assign"]],
	["capture", ["name", "assign", "append"]],
	["config_load", ["file", "section", "scope"]],
	["counter", ["name", "start", "skip", "direction", "print", "assign"]],
	["extend", ["file"]],
	["function", ["file"]],
	["for", ["to", "step", "max"]],
	["foreach", ["as", "name", "from", "key", "item"]],
	["include", ["file", "assign", "cache_lifetime", "compile_id", "cache_id", "scope"]],
	["section", ["name", "loop", "start", "step", "max", "show"]],
]);
